menu: #網站資料
  首頁: / || fas fa-home
  時間軸: /archives/ || fas fa-archive
  標籤: /tags/ || fas fa-tags
  分類: /categories/ || fas fa-folder-open
  照片: /Gallery/ || fas fa-images
  關於: /about/ || fas fa-heart
  #清單||fa fa-heartbeat:
  #音樂: /music/ || fas fa-music
  #電影: /movies/ || fas fa-video
  #友鏈: /link/ || fas fa-link

highlight_theme: light  #代碼高亮主題
highlight_copy: true #代碼複製
highlight_shrink: false #代碼框展開，有 '>' 打開

social: #社交圖標
  fab fa-github: https://github.com/Nickliu0811 || Github
  fas fa-envelope: mailto:nick8.liu@gmail.com || Email
  fa-solid fa-book: https://nickliu0811.github.io || blog

cover: 
  # 是否顯示文章封面
  index_enable: true 
  aside_enable: true
  archives_enable: true
  # 封面顯示的位置
  # 三個值可配置 left , right , both
  position: left
  # 當沒有設置cover時，默認的封面顯示
  default_cover: 
    - https://fastly.jsdelivr.net/gh/jerryc127/CDN@latest/cover/default_bg.png

post_meta: #文章頁相關配置
  page:
    date_type: created # created or updated or both 主頁文章日期是創建日或者更新日或都顯示
    date_format: date # date/relative 顯示日期還是相對日期
    categories: true # true or false 主頁是否顯示分類
    tags: true # true or false 主頁是否顯示標籤
    label: true # true or false 顯示描述性文字
  post:
    date_type: both # created or updated or both 文章頁日期是創建日或者更新日或都顯示
    date_format: date # date/relative 顯示日期還是相對日期
    categories: true # true or false 文章頁是否顯示分類
    tags: true # true or false 文章頁是否顯示標籤
    label: true # true or false 顯示描述性文字

# post_copyright:  #文章版權
#   enable: true
#   decode: false
#   author_href:
#   license: CC BY-NC-SA 4.0
#   license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# Post edit #文章編輯按鈕
# Easily browse and edit blog source code online.
post_edit:
  enable: false
  # url: https://github.com/user-name/repo-name/edit/branch-name/subdirectory-name/
  # For example: https://github.com/jerryc127/butterfly.js.org/edit/main/source/
  url: 

# post_pagination (分頁)
# value: 1 || 2 || false
# 1: The 'next post' will link to old post
# 2: The 'next post' will link to new post
# false: disable pagination
post_pagination: true

avatar: #頭像
  img: /img/avatar.png
  effect: true # 頭像會一直轉圈

footer: #博客年份
  owner:
    enable: true
    since: 2022

custom_text: Hi, welcome to my blog !

aside:
  enable: true
  hide: false
  button: true
  mobile: true # 手機頁面（ 顯示寬度 < 768px ）是否顯示aside內容
  position: right # left or right
  display:
    archive: true
    tag: true
    category: true
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: true
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: YYYY年MM月 # eg: YYYY年MM月 MMMM YYYY
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true

busuanzi: #訪問人數 busuanzi (UV 和 PV)
  site_uv: true
  site_pv: true
  page_pv: true

runtimeshow:
  enable: true
  publish_date: 2022/11/25  
  ##網頁開通時間
  #格式: 月/日/年 時間
  #也可以寫成 年/月/日 時間

# # Aside widget - Newest Comments
# newest_comments:
#   enable: true
#   sort_order: # Don't modify the setting unless you know how it works
#   limit: 6 #顯示的數量
#   storage: 10 # 設置緩存時間，單位 分鐘
#   avatar: true #是否顯示頭像

note: #圖外掛
  # Note tag style values:
  #  - simple    bs-callout old alert style. Default.
  #  - modern    bs-callout new (v2-v3) alert style.
  #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
  #  - disabled  disable all CSS styles import of note tag.
  style: simple
  icons: false
  border_radius: 3
  # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
  # Offset also applied to label tag variables. This option can work with disabled note tag.
  light_bg_offset: 0

# mermaid 流程圖
# see https://github.com/mermaid-js/mermaid
mermaid:
  enable: true
  # built-in themes: default/forest/dark/neutral
  theme:
    light: default
    dark: dark

# 主頁subtitle
subtitle:
  enable: false
  # Typewriter Effect (打字效果)
  effect: true
  startDelay: 300 # time before typing starts in milliseconds
  typeSpeed: 150 # type speed in milliseconds
  backSpeed: 50 # backspacing speed in milliseconds
  # loop (循環打字)
  loop: true
  # source 調用第三方服務
  # source: false 關閉調用
  # source: 1  調用一言網的一句話（簡體） https://hitokoto.cn/
  # source: 2  調用一句網（簡體） http://yijuzhan.com/
  # source: 3  調用今日詩詞（簡體） https://www.jinrishici.com/
  # subtitle 會先顯示 source , 再顯示 sub 的內容
  source: false
  # 如果關閉打字效果，subtitle 只會顯示 sub 的第一行文字
  sub:
    - 今日事今日畢
    - 時間總是不夠用